config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  require 'sidekiq/web'

  resources :loans do
    get '/dashboard', to: 'dashboard#index', as: 'dashboard'
  end

  namespace :admin do
    get 'dashboard', to: 'dashboard#index', as: 'dashboard'
    resources :loans do
      member do
        patch 'accept'
        post 'approve'
        post 'reject'
      end
    end
  end

  namespace :user do
    get 'dashboard', to: 'dashboard#index', as: 'dashboard'
    resources :loans do
      member do
        post 'repay'
        post 'confirm'
        post 'reject'
      end
    end
  end

  root 'home#index'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/loan.rb
class Loan < ApplicationRecord
  belongs_to :user

  enum state: { requested: 'requested', approved: 'approved', open: 'open', closed: 'closed', rejected: 'rejected', repaid: 'repaid' }

  include AASM

  aasm column: 'state' do
    state :requested, initial: true
    state :approved, :open, :closed, :rejected, :repaid

    event :approve do
      transitions from: :requested, to: :approved
    end

    event :reject do
      transitions from: [:requested, :approved], to: :rejected
    end

    event :confirm do
      transitions from: :approved, to: :open
    end

    event :close do
      transitions from: :open, to: :closed
    end
  end


  def close!
    self.update(state: 'closed')
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :loans
  before_create :set_default_user

  def admin?
    role == 'admin'
  end

  private

  def set_default_user
    self.wallet_amount = 10000
    self.role = "user"
    self.name = self.email.split('@').first
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_admin

  def index
    @loan_requests = Loan.requested.includes(:user)
    @active_loans = Loan.open.includes(:user)
    @closed_loans = Loan.closed.includes(:user)
    @approved_loans = Loan.approved.includes(:user)
    @rejected_loans = Loan.rejected.includes(:user)
  end

  private

  def authorize_admin
    redirect_to root_path, alert: 'Access denied.' unless current_user.admin?
  end
end

app/controllers/admin/loans_controller.rb
class Admin::LoansController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_admin

  def show
    @loan = Loan.find(params[:id])
    @loan_transactions = @loan.amount
    respond_to do |format|
      format.html { render :show }
      format.json { render json: { loan: @loan, transactions: @loan_transactions } }
    end
  end

  def reject
    @loan = Loan.find(params[:id])

    if @loan.requested?
      @loan.reject!
      redirect_to admin_dashboard_path
    end
  end

  def accept
    @loan = Loan.find(params[:id])
    
    if @loan.requested?
      new_interest_rate = params[:loan][:interest_rate]
      new_interest_rate = new_interest_rate.present? ? new_interest_rate : 0.05

      @loan.update(interest_rate: new_interest_rate)

      ActiveRecord::Base.transaction do
        @loan.approve!
        redirect_to admin_dashboard_path
      end
    end
    respond_to do |format|
      format.html { redirect_to admin_loan_path(@loan) }
      format.js
    end
  end

  private

  def authorize_admin
    redirect_to root_path, alert: 'Access denied.' unless current_user.role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  protected

  def after_sign_in_path_for(resource)
    if resource.role == 'admin'
      admin_dashboard_path
    else
      user_dashboard_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to user_dashboard_index_path
    else
      render 'welcome'
    end
  end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :authenticate_user!
  before_action :set_loan, only: [:show, :approve, :confirm, :repay]

  def new
    @loan = current_user.loans.build
  end

  def create
    @loan = current_user.loans.build(loan_params)
    @loan.total_amount = @loan.amount
    @loan.interest_rate = 5
    @loan.requested!

    if @loan.save
      redirect_to user_dashboard_path
    else
      render :new
    end
  end
  private
  def set_loan
    @loan = Loan.find(params[:id])
  end
  def loan_params
    params.require(:loan).permit(:amount, :interest_rate)
  end
end

app/controllers/user/dashboard_controller.rb
class User::DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @active_loans = current_user.loans.where(state: ["requested", "approved","open"])

    @repaid_loans = current_user.loans.where(state: "closed")

    @rejected_loans = current_user.loans.where(state: "rejected")
  end
end

app/controllers/user/loans_controller.rb
class User::LoansController < ApplicationController
  before_action :authenticate_user!
  before_action :set_loan, only: [:show, :repay, :confirm, :reject]

  def index
    @loans = current_user.loans
  end

  def new
    @loan = current_user.loans.build
  end
  
  def show
    @loan = Loan.find(params[:id])
    @loan_transactions = @loan.amount
    respond_to do |format|
      format.html { render :show }
      format.json { render json: { loan: @loan, transactions: @loan_transactions } }
    end
  end

  def confirm
    @loan = current_user.loans.find(params[:id])
    @admin = User.where(role: 'admin').first
    if @loan.approved?
      ActiveRecord::Base.transaction do
        admin_wallet = @admin.wallet_amount - @loan.amount
        @admin.update!(wallet_amount: admin_wallet)
        user_wallet = @loan.user.wallet_amount + @loan.amount
        @loan.user.update!(wallet_amount: user_wallet)
        @loan.open!
        InterestCalculationWorker.perform_in(5.minutes, @loan.id)
        LoanDebitingWorker.perform_in(5.minutes, @loan.id)
        redirect_to @loan
      end
    end
  end

  def reject
    @loan = current_user.loans.find(params[:id])

    if @loan.approved?
      @loan.reject!

      redirect_to user_dashboard_path(@loan)
    end
  end

  def repay
    @loan = current_user.loans.find(params[:id])
    if @loan.may_close?
      ActiveRecord::Base.transaction do
        user_wallet = current_user.wallet_amount - @loan.total_amount
        current_user.update!(wallet_amount: user_wallet)
        admin = User.find_by(role: 'admin')
        admin_wallet = admin.wallet_amount + @loan.total_amount
        admin.update!(wallet_amount: admin_wallet)
        @loan.close!

        scheduled_set = Sidekiq::ScheduledSet.new
        interest_worker_jobs = scheduled_set.select { |job| job.args.first == ['LoanInterestWorker', 'InterestCalculationWorker'] && job.args.last == [loan_id] }
        interest_worker_jobs.each(&:delete)
      end
    end
    redirect_to @loan
  end

  private

  def set_loan
    @loan = current_user.loans.find(params[:id])
  end

  def loan_params
    params.require(:loan).permit(:amount, :interest_rate)
  end
end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/admin/dashboard/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Admin Dashboard</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <style>
    .container-dashboard {
      background-color: #EEF0E5;
      margin-top: 40px;
      border-radius: 10px;
      padding: 20px;
    }

    h1, h2 {
      color: #007bff;
    }

    .list-group-item {
      border: 1px solid #ddd;
    }

    .list-group-item:hover {
      background-color: #f8f9fa;
    }

    .btn-sign-out {
      background-color: #dc3545;
      border: none;
    }

    .btn-sign-out:hover {
      background-color: #c82333;
    }
    .back {
      background-color: #B6C4B6;
    }
  </style>
</head>
<body class="back">

  <div class="container container-dashboard">
    <div class="row">
      <div class="col-md-8">
        <h1>Admin Dashboard</h1>
        <p><strong>Wallet Balance:</strong> <%= current_user.wallet_amount %></p>

        <h2 class="mt-4">Loan Requests</h2>
        <% if @loan_requests.any? %>
          <ul class="list-group">
            <% @loan_requests.each do |loan| %>
              <li class="list-group-item">
                <%= link_to "Amount #{loan.amount}", admin_loan_path(loan) %> -
                Requested by <%= loan.user.name %>
              </li>
            <% end %>
          </ul>
        <% else %>
          <p>No loan requests.</p>
        <% end %>
      </div>

      <div class="col-md-4">
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn btn-danger btn-sign-out float-right mt-2' %>
      </div>
    </div>

    <div class="row mt-4">
      <div class="col-md-6">
        <h2>Active Loans</h2>
        <% if @active_loans.any? %>
          <ul class="list-group">
            <% @active_loans.each do |loan| %>
              <li class="list-group-item">
                Name: <%= loan.user.name %> |
                Amount: <%= loan.amount %> |  
                Interest rate <%= loan.interest_rate %> %
              </li>
            <% end %>
          </ul>
        <% else %>
          <p>No active loans.</p>
        <% end %>
      </div>

      <div class="col-md-6">
        <h2>Closed Loans</h2>
        <% if @closed_loans.any? %>
          <ul class="list-group">
            <% @closed_loans.each do |loan| %>
              <li class="list-group-item">
                Name: <%= loan.user.name %> | 
                Amount: <%= loan.amount %> | 
                Amount Received: <%= loan.total_amount %>
              </li>
            <% end %>
          </ul>
        <% else %>
          <p>No closed loans.</p>
        <% end %>
      </div>
      <div class="col-md-6">
        <h2>Approved Loans</h2>
        <% if @approved_loans.any? %>
          <ul class="list-group">
            <% @approved_loans.each do |loan| %>
              <li class="list-group-item">
                Name: <%= loan.user.name %> | 
                Amount: <%= loan.amount %>
              </li>
            <% end %>
          </ul>
        <% else %>
          <p>No approved loans.</p>
        <% end %>
      </div>
      <div class="col-md-6">
        <h2>Rejected Loans</h2>
        <% if @rejected_loans.any? %>
          <ul class="list-group">
            <% @rejected_loans.each do |loan| %>
              <li class="list-group-item">
                Name: <%= loan.user.name %> | 
                Amount: <%= loan.amount %> |
                Status: <%= loan.state %>
              </li>
            <% end %>
          </ul>
        <% else %>
          <p>No rejected loans.</p>
        <% end %>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>

app/views/admin/loans/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Show Loan Details</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <style>
    body {
      margin-top: 4rem;
    }

    h1 {
      margin-bottom: 1.5rem;
      color: #007bff;
    }

    dl.row {
      margin-bottom: 2rem;
    }

    .form-group {
      margin-bottom: 1.5rem;
    }

    .btn {
      margin-right: 1rem;
    }

    .list-group {
      margin-top: 2rem;
    }

    .list-group-item {
      margin-bottom: 0.5rem;
      border: 1px solid #ddd;
    }

    .list-group-item:hover {
      background-color: #f8f9fa;
    }
  </style>
</head>
<body>

  <div class="container">
    <h1>Loan Details</h1>

    <div class="container">
      <dl class="row">
        <dt class="col-sm-3">Loan ID:</dt>
        <dd class="col-sm-9"><%= @loan.id %></dd>

        <dt class="col-sm-3">Amount:</dt>
        <dd class="col-sm-9"><%= @loan.amount %></dd>
      </dl>

      <%= form_for @loan, url: accept_admin_loan_path(@loan), method: :patch, remote: true do |f| %>
        <div class="form-group">
          <%= f.label :interest_rate %>
          <%= f.text_field :interest_rate, id: 'interest-rate-field', class: 'form-control' %>
        </div>

        <%= f.submit 'Approve Loan', class: 'btn btn-success mb-4' %>
      <% end %>

      <%= button_to 'Reject Loan', reject_admin_loan_path(@loan), method: :post, class: 'btn btn-danger' %>

      <h2 class="mt-4">Transaction History</h2>

      <% if @loan_transactions.is_a?(Array) && @loan_transactions.any? %>
        <ul class="list-group">
          <% @loan_transactions.each do |transaction| %>
            <li class="list-group-item">
              Transaction ID: <%= transaction.id %>, Amount: <%= transaction.amount %>
            </li>
          <% end %>
        </ul>
      <% else %>
        <p class="ml-2">No transactions found.</p>
      <% end %>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>

app/views/home/welcome.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Welcome to Loan Management</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <style>
    body {
      background: url('https://img.freepik.com/free-photo/growth-economy-with-coins-concept_23-2148525276.jpg?w=1800&t=st=1702736951~exp=1702737551~hmac=b1f16ea115a03ef7c2553e8d4a9b002c577c372a72c2ba4e5cdba3d539bec857') no-repeat center center fixed;
      background-size: cover;
      color: #fff;
      height: 100vh;
      display: flex;
      justify-content: center;
      align-items: center;
    }

    .container-custom {
      background-color: #B6C4B6;
      border-radius: 10px;
      background-color: rgba(48, 77, 48, 0.5);
      inline-size: fit-content;
      margin: auto;
      text-align: center;
      padding: 100px;
    }

    .btn-custom {
      margin-top: 20px;
    }
    .display-4 {
      font-weight: bold;
  }
  </style>
</head>
<body class="bg-light">

  <div class="container-custom">
    <div>
      <h1 class="display-4">Welcome to Loan Management</h1>
      <p class="lead">Explore our loan management system to manage your loans efficiently.</p>

      <div class="mt-4">
        <%= link_to 'Sign in', new_user_session_path, class: 'btn btn-primary mr-2 btn-custom' %>
        <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-secondary btn-custom' %>
      </div>
    </div>
  </div>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LoanManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/loans/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Loan Details</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <style>
    .container {
      margin-top: 50px;
    }

    h1 {
      color: #007bff;
    }

    .card {
      background-color: #EEF0E5;
      margin-top: 20px;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

    .card-body {
      padding: 20px;
    }

    .btn-secondary {
      margin-top: 20px;
    }
    .bg-light{
      background-color: #B6C4B6 !important;
    }
  </style>
</head>
<body class="bg-light">

  <div class="container mt-5">
    <h1>Loan Details</h1>

    <div class="card">
      <div class="card-body">
        <p class="card-text"><strong>Name:</strong> <%= @loan.user.name %></p>
        <p class="card-text"><strong>Loan Amount:</strong> <%= @loan.amount %></p>
        
        <% if @loan.state == 'closed' %>
          <p class="card-text"><strong>Amount Paid:</strong> <%= @loan.total_amount %></p>
        <% end %>
        
        <p class="card-text"><strong>Interest Rate:</strong> <%= @loan.interest_rate %> % </p>
        <p class="card-text"><strong>Current State:</strong> <%= @loan.state %></p>
      </div>
    </div>

    <%= button_to 'Back', user_dashboard_path, method: :get, class: 'btn btn-secondary mt-3' %>
  </div>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>

app/views/user/dashboard/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>User Dashboard</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <style>
    body {
      background-color: #B6C4B6;
    }

    .container-dashboard {
      height: 90vh;
      background-color: #EEF0E5;
      margin: 40px auto;
      border-radius: 10px;
      padding: 32px;
      overflow: scroll;
    }

    h1 {
      color: #2C3E50;
    }

    .welcome-message {
      font-size: 20px;
      margin-bottom: 20px;
      color: #154360;
    }

    .wallet-info {
      margin-bottom: 20px;
    }

    .alert-warning {
      margin-top: 20px;
    }

    .btn-action {
      margin-top: 10px;
    }

    .list-group-item {
      background-color: #ECF0F1;
      border: 1px solid #BDC3C7;
      margin-bottom: 10px;
    }

    .repaid-loans {
      margin-top: 30px;
    }

    .list-group-item:hover {
      background-color: #D5D8DC;
    }

    .list-group-item a {
      color: #3498DB;
    }
  </style>
</head>
<body>

  <div class="container container-dashboard">
    <div class="row">
      <div class="col-md-8">
        <h1>User Dashboard</h1>
        <p class="welcome-message"><strong>Welcome <%= current_user.name %>!</strong></p>
        
        <div class="wallet-info">
          <p><strong>Wallet Balance:</strong> <%= current_user.wallet_amount %></p>

          <% if current_user.wallet_amount.zero? %>
            <div class="alert alert-warning">
              You have insufficient funds in your wallet.
            </div>
          <% else %>
            <%= link_to 'Request New Loan', new_user_loan_path, class: 'btn btn-primary btn-action' %>
          <% end %>
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn btn-secondary btn-action' %>
        </div>

        <div class="loan-list">
          <h2 class="mt-4">Active Loans</h2>
          <% if @active_loans.any? %>
            <div class="list-group">
              <% @active_loans.each do |loan| %>
                <div class="list-group-item">
                  Amount: <%= loan.total_amount %> -
                  Interest Rate: <%= loan.interest_rate %> % -
                  Status: <%= loan.state %>
                  
                  <% if loan.state == 'open' %>
                    <%= link_to 'Repay Loan', repay_user_loan_path(loan), method: :post, data: { confirm: 'Are you sure you want to repay this loan?' }, class: 'btn btn-primary btn-sm float-right btn-action' %>
                  <% end %>
                  
                  <% if loan.state == 'approved' %>
                    <%= link_to 'Confirm', confirm_user_loan_path(loan), method: :post, data: { confirm: 'Are you sure you want to confirm this loan?' }, class: 'btn btn-primary btn-sm float-right btn-action' %>
                  <% end %>
                  
                  <% if loan.state == 'approved' %>
                    <%= link_to 'Reject', reject_user_loan_path(loan), method: :post, data: { confirm: 'Are you sure you want to reject this loan?' }, class: 'btn btn-primary btn-sm float-right btn-action' %>
                  <% end %>
                </div>
              <% end %>
            </div>
          <% else %>
            <p>No active loans.</p>
          <% end %>
        </div>

        <div class="loan-list repaid-loans">
          <h2 class="mt-4">Repaid Loans</h2>
          <% if @repaid_loans.any? %>
            <div class="list-group">
              <% @repaid_loans.each do |loan| %>
                <div class="list-group-item">
                  Amount: <%= loan.amount %> -
                  Amount Paid: <%= loan.total_amount %> -
                  Interest Rate: <%= loan.interest_rate %> % -
                  Status: <%= loan.state %>
                </div>
              <% end %>
            </div>
          <% else %>
            <p>No repaid loans.</p>
          <% end %>
        </div>

        <div class="loan-list repaid-loans">
          <h2 class="mt-4">Rejected Loans</h2>
          <% if @rejected_loans.any? %>
            <div class="list-group">
              <% @rejected_loans.each do |loan| %>
                <div class="list-group-item">
                  Amount: <%= loan.amount %> -
                  Interest Rate: <%= loan.interest_rate %> % -
                  Status: <%= loan.state %>
                </div>
              <% end %>
            </div>
          <% else %>
            <p>No repaid loans.</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>

app/views/user/loans/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>New Loan</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <style>
    body {
      background-color: #B6C4B6;
    }

    .container {
      max-width: 400px;
      border-radius: 10px;
      background-color: #EEF0E5;
      margin: 40px auto;
      padding: 40px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    h1 {
      margin-bottom: 30px;
      text-align: center;
      color: #007bff;
    }

    .form-container {
      max-width: 100%;
    }

    .form-group {
      margin-bottom: 20px;
    }

    .numeric {
      width: 100%;
    }

    .btn-submit {
      width: 100%;
    }

    .amount-label {
      font-weight: bold;
    }
  </style>
</head>
<body>

  <div class="container">
    <h1>New Loan</h1>

    <div class="form-container">
      <%= form_for @loan do |f| %>
      <div class="form-group">
        <%= f.label :amount, class: 'amount-label' %>
        <%= f.number_field :amount, class: 'form-control numeric', placeholder: 'Enter loan amount', required: true %>
      </div>

        <%= f.submit 'Create Loan', class: 'btn btn-primary btn-submit' %>
      <% end %>
      <div class="text-center">
        <%= button_to 'Back', user_dashboard_path, method: :get, class: 'btn btn-secondary mt-3' %>
      </div>
    </div>
  </div>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>